### ISSUE TITLE
How to login bot

### ISSUE THREAD

**Issue by Maryam-Rajput** [0x3EF8/Hexabot#10]
There is no file or instruction provided in readme.md that weere we need to paste our appstate

**Comment by mrepol742** [comment]
According to the following line of code
https://github.com/0x3EF8/Hexabot/blob/main/index.js#L12C1-L17C3 and
https://github.com/0x3EF8/Hexabot/blob/main/index.js#L81C7-L82C1

Appstate should be place in 0x3/credentials/cookies folder

You can name the file it as you like just make sure it ends in .json
