### ISSUE TITLE
auto reply.

### ISSUE THREAD

**Issue by Savage-Army** [0x3EF8/Hexabot#5]
previous version was better . that one isn't replying auto.

**Comment by mrepol742** [comment]
@Savage-Army hello can you clarify what do you mean by auto and how can we reproduce the problem? giving just it doesn't make sense at all.

**Comment by Savage-Army** [comment]
I mean ,in the the past version Whenever I typed something like : How are you? (anything including question mark) it replied..but in that version I doesn't give any ans . specially in the facebook community chat. In inbox its working perfectly.

**Comment by mrepol742** [comment]
Oh i get it. The author are doing a cost effective solutions in reducing the amount to tokens used per month. In order for  HexaBot to effectively service everyone this is the effective way of saving tokens. Mentioning the bot name/prefix isn't a hastle though.
