### ISSUE TITLE
Bard command not working.

### ISSUE THREAD

**Issue by Savage-Army** [0x3EF8/Hexabot#6]
Hello there,
bard command isn't working anymore.
I tried changing "__Secure-1PSID" many times. But it didn't work.

![Screenshot (41)](https://github.com/0x3EF8/Hexabot/assets/116685576/f0da1389-fbef-40e7-9925-40b96761dfb7)

**Comment by 0x3EF8** [comment]
Hello

It seems like you're facing issues with the bard command, but there's a solution for it. You can use the browser extension provided at this link: BardAI-SessionManager https://github.com/lester51/BardAI-SessionManager/releases/tag/BardAI. Import the extension into your browser, visit the Bard website at https://bard.google.com log in to your account, and then click the extension to copy the cookies then replace the cookies in the api_config.json file under the bard_cookies section with the new ones. This should resolve the problem.

**Comment by 0x3EF8** [comment]
> Hello there, bard command isn't working anymore. I tried changing "__Secure-1PSID" many times. But it didn't work.
> 
> ![Screenshot (41)](https://user-images.githubusercontent.com/116685576/279602908-f0da1389-fbef-40e7-9925-40b96761dfb7.png)



> Hello there, bard command isn't working anymore. I tried changing "__Secure-1PSID" many times. But it didn't work.
> 
> ![Screenshot (41)](https://user-images.githubusercontent.com/116685576/279602908-f0da1389-fbef-40e7-9925-40b96761dfb7.png)




Hello

It seems like you're facing issues with the bard command, but there's a solution for it. You can use the browser extension provided at this link: BardAI-SessionManager https://github.com/lester51/BardAI-SessionManager/releases/tag/BardAI. Import the extension into your browser, visit the Bard website at https://bard.google.com log in to your account, and then click the extension to copy the cookies then replace the cookies in the api_config.json file under the bard_cookies section with the new ones. This should resolve the problem.

**Comment by 0x3EF8** [comment]
Hello

It seems like you're facing issues with the bard command, but there's a solution for it. You can use the browser extension provided at this link: BardAI-SessionManager https://github.com/lester51/BardAI-SessionManager/releases/tag/BardAI. Import the extension into your browser, visit the Bard website at https://bard.google.com/ log in to your account, and then click the extension to copy the cookies then replace the cookies in the api_config.json file under the bard_cookies section with the new ones. This should resolve the problem.

**Comment by 0x3EF8** [comment]
Hello @Savage-Army,

It seems like you're facing issues with the bard command, but there's a solution for it. You can use the browser extension BardAI-SessionManager https://github.com/lester51/BardAI-SessionManager/releases/tag/BardAI. Import the extension into your browser, visit the Bard website at https://bard.google.com/ log in to your account, and then click the extension to copy the cookies then replace the cookies in the api_config.json file under the bard_cookies section with the new ones. This should resolve the problem.

**Comment by Savage-Army** [comment]
@0x3EF8 still not working.

**Comment by 0x3EF8** [comment]
can you send some screenshot?
